### ISSUE TITLE
Editing and removing licences impossible

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/demo-inveniordm#66] opened 2022-01-20 14:02 UTC
Package version (if known): current invenio-demo (2022-01-20) and v7 (our own instance)

## Describe the bug

Licenses can not be edited or removed.

## Steps to Reproduce
1. Sign up
2. Go to https://inveniordm.web.cern.ch/uploads/new
- Error 1:
  1. Click on "Edit" "Creative Commons Attribution 4.0 International"
  2. Change the license
  3. Click "Change license"
  4. Nothing happens
- Error 2:
  1. Click "Remove" "Creative Commons Attribution 4.0 International"
  2. Nothing happens

## Expected behavior
For Error 1: License is changed
For Error 2: License is removed

## Additional context
Same behaviour for "add standard" and "add custom" licences.

**Comment by fenekku** [comment] 2022-01-20 14:17
Duplicate of <https://github.com/inveniosoftware/react-invenio-deposit/issues/387>. WIll close :)

**Closed by fenekku** 2022-01-20 14:17 UTC
Labels: bug
